name: trackizer
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # PERBAIKAN: Gunakan versi 5.0.0 untuk mengatasi konflik dengan Flutter 3.24+
  carousel_slider: ^5.0.0 
  
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  intl: ^0.18.0
  
  # Local libraries
  calendar_agenda:
    path: dev_lib/calendar_agenda
  card_swiper:
    path: dev_lib/card_swiper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700